### ISSUE TITLE
Is it possible to made an english version ?

### ISSUE THREAD

**Issue by cloudshooterhuman** [leerduo/InterviewQuestion#1]
Hello,

Thanks for sharing this interview, please can you make this interview in  english ?

Regards,

**Comment by leerduo** [comment]
@selmanon  Hi，I am now busy looking for work, no time to deal with this matter，sorry for that。And you can find some interview questions here(http://skillgun.com/android/interview-questions-and-answers)，hope this can help you.

**Comment by cloudshooterhuman** [comment]
@leerduo Thanks for the website it's useful
