### ISSUE TITLE
关于设置文中提到的横竖屏切换

### ISSUE THREAD

**Issue by chufengma** [leerduo/InterviewQuestion#2]
```
设置Activity的android:configChanges="orientation"时，切屏还是会重新调用各个生命周期，切横、竖屏时只会执行一次
```

在我的测试下
这句话不是不完整，而是有问题。。。

<strong>设置Activity的android:configChanges="orientation"时(api>12 加上ScreenSIze)，不会调用默认的处理方式，而是转而调用onConfigurationChanged</strong>

**Comment by leerduo** [comment]
@chufengma 感谢提出！

**Comment by Caij** [comment]
android:configChanges 不设置的时候，切横、竖屏生命周期也只会一次。使用的是n5 6.0系统
